version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:${DB_PORT}

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf


  app:
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
    command: ./wait-for-it.sh db:5432 -- python run.py


  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - db