version: '3.6'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:${DB_PORT}

  api:
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: [ "./wait-for-it.sh", "db:5432", "--", "python", "run.py" ]

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - db